def count_DNA_nucleotides(string):
    A = 0
    C = 0
    G = 0
    T = 0
    for i in string:
        if i == 'A':
            A += 1
        if i == 'C':
            C += 1
        if i == 'G':
            G += 1
        if i == 'T':
            T += 1
    print(A, C, G, T)
    return


count_DNA_nucleotides('TCGCGCTGGCAGCTCTTTCTGTATCTCTGGGATGGATCTTCTACGGTCGTGGGCACTGGCGCAACACAGATACGCTACACGGATGCTACGCGTATGAACCCTGTAAAGTACCGAACGCAATATCTCAGCTTTTTCACTGTAGGTAAGCTTTTTTTACAGTCCCCTGAATCGCACGCCAAACGCTCGGCCGTGTACATGCCTGGAGAAACTAGGTAGCCGGGAACGAGTAATAGTTGGGTGGTGTATTGTTTACGAATGATTGACTGTGCAACGCTCACTCGACAGCACGCGATCTCGAATAGCTTTAGCACGATTCTCTTCCTATTGCGTTGTAAGGGCAATCTGACGCAATGAGAAGTGCTTTATGTAGGCCCGGTTGGACAGTTATTAAGCTGTCTAGCTGAATGCGGAGTCCCGTCTGCCTCTGGCGCGTGCATGCGACATATACTCCCTCCCTCTGTCCTGGTTGTCTCACCTACAACTAGGCCGGTCATGGAACCGGGACGAACGACGTAAGCGGGAGACTAAATCGATCTATTTATCCTCGTAGATTTGATGCACCCTTAGAGATACAACGTCCTTGGAACAGTTGAATCCCGACACAGCAAGGACTTTACCCAGGCCAGCTGAATTGTTCCGTAAGTTGCAGAGGTAAGTTGTTTATCAGTCCCAGCAAATAGCTCCGGCATTTACTATCATACACTCGAACCGACTTCCCATCGTAGGGGCTAGGACAACCAAACGCATTATAGCCTACGCTTCCGTAGACGCCAGAGAGAGGTCGCGGAGCGTGGGAATGCTCAGTGGAGCCCGGCATTAGGTCTAAGTACAGA')
