def complement(DNA):
    result = []
    for i in list(DNA):
        if i == 'A':
            result.append('T')
        elif i == 'T':
            result.append('A')
        elif i == 'C':
            result.append('G')
        elif i == 'G':
            result.append('C')
    result.reverse()
    return ''.join(result)


print(complement('CATAGATACTCCTAAGGACCGTAAGTCAAAGTAATATGCAGCGTAACTCGCCATACCTAAGATCCTAGACGCTGGGGTCTCTTGTAAATATGTCGGTGGACAAGGTTATAATCGTGGGCAGAGCGATTGCTTCCGTGTCTGTGCGTTATGCGGTACGAAACGGGCGCATTCACGTGGCGAAGTATACCGAGACAAGATAATTTTCCCCACGTGATTCCTTCATCCATGCATTGGTCATTCCCGTCATCATGTGGGTTACTCAACCGGTGGGGACTTCGCGGACATTCTAGCTGAGACCCACCGACATAGCTTGAGTATAATCTAATCATACAGTGAGGAGTATACACTTAAGGCTCTAATTTTCGAGTCAAGCCGTTTAACATGTACAACCACAGCTTAGCGATGAAGCTTCTGAGTCCGTCATTTAATTTTTAAAGAACGAATCCATGGCTTCCGCGAATTGCTGCCGGCTAATACTAATGACCTACATAAAGGGAATTCTTGCATATAGCAAAGGTTGGGACTACTTCCTACCCACCATCTCCAGCAGGGCTCTGTGCAGCAAGGGGTTGTCATACCTACGCGGTGCTGTCCTTGGTGCGTAATGCAAACAGCGGATCTTACTTCCAAATGATCGGGGTCAAGATCGTGAGGATATTAGGGGATTGGTAGCTGTATTGGACCGATAGGGTTGAGAACTAGACGCTTGGCTAGCACCTTCCTCTGCTGATAATAGCAAGATTGTGATCGCTAAGTACGATAATTCCGTGCGCAGTCGAAGCACATAGGATAAACTTTATTCGGCAACTCTCCCGTGGATTTAATTCATATATCGGCGCGTTAACATTAAGAACAATGCAGCGTCGTTCACGGCCGATGTTGGTCAGCTTTGAGTTGAAGAAAACGGGTCTTGGGCG'))
